
# Site settings
title: Park School Mathematics
email: parkmathblog@parkschool.net
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/parkmath/" # the subpath of your site, e.g. /blog/
url: "http://parkmath.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: lessons
    values:
      layout: lesson


# Prose metadata
prose:
  rooturl: lessons
  siteurl: "http://parkmath.github.io/parkmath"
  media: lessons/images
  metadata:
    lessons:
      - name: book
        field:
          element: number
          label: Book Number
          value: 0
      - name: lesson
        field:
          element: number
          label: Lesson Number
          value: 0
      - name: title
        field:
          element: text
          label: Title
          value: ''
      - name: layout
        field:
          element: hidden
          value: lesson
          
  
